export const ADD_TODO = 'ADD_TODO'
export const INIT_TODOS = 'INIT_TODOS'
export const UPDATE_TODO = 'UPDATE_TODO'
export const EDITING_TODO = 'EDITING_TODO'

export const ADD_WATERMELON = 'ADD_WATERMELON'
export const INIT_WATERMELON = 'INIT_WATERMELON'
export const UPDATE_WATERMELON = 'UPDATE_WATERMELON'

export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAILURE = 'VERIFY_USER_FAILURE'

export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_WATERMELON_SUCCESS = 'FETCH_WATERMELON_SUCCESS'

export const HAS_READ_USER_ERROR = 'HAS_READ_USER_ERROR'
